export const menuItems = [
  // Chocolate items
  {
    name: "Chocolate Cake",
    price: "$200.00",
    oldPrice: "$250.00",
    image: "../images/download.jpeg",
    category: "chocolate",
  },
  {
    name: "Hot Chocolate",
    price: "$180.00",
    oldPrice: "$220.00",
    image: "../images/hotchoclate.jpeg",
    category: "chocolate",
  },
  {
    name: "Chocolate Brownie",
    price: "$150.00",
    oldPrice: "$180.00",
    image: "../images/choclatebrownie.jpeg",
    category: "chocolate",
  },
  {
    name: "Chocolate Muffin",
    price: "$120.00",
    oldPrice: "$150.00",
    image: "../images/chocmuffin.jpeg",
    category: "chocolate",
  },
  {
    name: "Dark Chocolate",
    price: "$250.00",
    oldPrice: "$300.00",
    image: "../images/download (1).jpeg",
    category: "chocolate",
  },
  {
    name: "Chocolate Truffle",
    price: "$280.00",
    oldPrice: "$320.00",
    image: "../images/download (2).jpeg",
    category: "chocolate",
  },

  // Coffee items
  {
    name: "Americano Coffee",
    price: "$325.00",
    oldPrice: "$348.00",
    image: "../images/americano.jpeg",
    category: "coffee",
  },
  {
    name: "Caffè Latte",
    price: "$325.00",
    oldPrice: "$348.00",
    image: "../images/cafe latte.jpeg",
    category: "coffee",
  },
  {
    name: "Espresso Ristretto",
    price: "$325.00",
    oldPrice: "$348.00",
    image: "../images/ristretto.jpeg",
    category: "coffee",
  },
  {
    name: "Latte Macchiato",
    price: "$325.00",
    oldPrice: "$348.00",
    image: "../images/machiatto.jpeg",
    category: "coffee",
  },
  {
    name: "Espresso Lungo",
    price: "$325.00",
    oldPrice: "$348.00",
    image: "../images/lungo.jpeg",
    category: "coffee",
  },
  {
    name: "Coffee with Milk",
    price: "$325.00",
    oldPrice: "$348.00",
    image: "../images/coffe with milk.jpeg",
    category: "coffee",
  },

  // Sandwiches items
  {
    name: "Veggie Sandwich",
    price: "$150.00",
    oldPrice: "$180.00",
    image: "../images/veggiesandwhich.jpeg",
    category: "sandwiches",
  },
  {
    name: "Club Sandwich",
    price: "$200.00",
    oldPrice: "$230.00",
    image: "../images/clubsandwhich.jpeg",
    category: "sandwiches",
  },
  {
    name: "Grilled Cheese Sandwich",
    price: "$170.00",
    oldPrice: "$190.00",
    image: "../images/greencheese.jpeg",
    category: "sandwiches",
  },
  {
    name: "Chicken Sandwich",
    price: "$220.00",
    oldPrice: "$250.00",
    image: "../images/chicken.jpeg",
    category: "sandwiches",
  },
  {
    name: "Tuna Sandwich",
    price: "$240.00",
    oldPrice: "$280.00",
    image: "../images/tuna.jpeg",
    category: "sandwiches",
  },
  {
    name: "Ham Sandwich",
    price: "$210.00",
    oldPrice: "$260.00",
    image: "../images/hamsandwhich.jpeg",
    category: "sandwiches",
  },

  // Sweets items
  {
    name: "Cheesecake",
    price: "$300.00",
    oldPrice: "$350.00",
    image: "../images/cheesecake.jpeg",
    category: "sweets",
  },
  {
    name: "Brownie",
    price: "$180.00",
    oldPrice: "$200.00",
    image: "../images/brownie.jpeg",
    category: "sweets",
  },
  {
    name: "Macarons",
    price: "$250.00",
    oldPrice: "$300.00",
    image: "../images/macrons.jpeg",
    category: "sweets",
  },
  {
    name: "Donut",
    price: "$150.00",
    oldPrice: "$180.00",
    image: "../images/donut.jpeg",
    category: "sweets",
  },
  {
    name: "Cupcake",
    price: "$200.00",
    oldPrice: "$250.00",
    image: "../images/cupcake.jpeg",
    category: "sweets",
  },
  {
    name: "Tiramisu",
    price: "$280.00",
    oldPrice: "$320.00",
    image: "../images/tiramisu.jpeg",
    category: "sweets",
  },

 
  // Green Tea items
  {
    name: "Jasmine Green Tea",
    price: "$160.00",
    oldPrice: "$190.00",
    image: "../images/jasminetea.jpeg",
    category: "green tea",
  },
  {
    name: "Matcha Latte",
    price: "$200.00",
    oldPrice: "$230.00",
    image: "../images/mmatchalatte.jpeg",
    category: "green tea",
  },
  {
    name: "Sencha",
    price: "$180.00",
    oldPrice: "$220.00",
    image: "../images/sencha.jpeg",
    category: "green tea",
  },
  {
    name: "Gyokuro",
    price: "$240.00",
    oldPrice: "$280.00",
    image: "../images/gyokuro.jpeg",
    category: "green tea",
  },
  {
    name: "Hojicha",
    price: "$220.00",
    oldPrice: "$260.00",
    image: "../images/hojicha.jpeg",
    category: "green tea",
  },
  {
    name: "Genmaicha",
    price: "$200.00",
    oldPrice: "$240.00",
    image: "../images/jenmicha.jpeg",
    category: "green tea",
  },
];
